# Generated by Django 4.1 on 2022-08-12 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='dia_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 17, 27, 33, 861080, tzinfo=datetime.timezone.utc)),
        ),
    ]
