# Generated by Django 4.1 on 2022-08-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_owner_pais_alter_owner_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='edad',
            field=models.IntegerField(max_length=3),
        ),
    ]
